name: Build Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build Plugin
      run: dotnet build Eyecuthulu.csproj -c Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: dll
        path: |
          **/bin/Release/*.dll
